#!/usr/bin/env node
// YTF Pipeline — aggregates every tool's summary.json (+ manual data-entry records)
// into ONE dashboard the phone panel and the supermega-platform can read.
//
//   ops extractor  ─┐
//   sources-tool    ├─►  pipeline.mjs  ─►  out/ytf-dashboard.json
//   tyre-analysis   │                      out/YTF-MASTER-BRIEF.md
//   nr-export       │                      (+ copy to ../supermega-remote/public/)
//   competitive    ─┘
//   manual-entries/*.json (from the data-entry form) ─┘
//
// Usage: node pipeline.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(DIR, 'out');
fs.mkdirSync(outDir, { recursive: true });

const readJson = (p) => { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; } };

// 1) collect every summary.json (base extractor + each tool)
const summaries = [];
const base = readJson(path.join(outDir, 'summary.json'));
if (base) summaries.push({ name: 'ops', source: 'gmail', ...base });

const toolsDir = path.join(DIR, 'tools');
if (fs.existsSync(toolsDir)) {
  for (const tool of fs.readdirSync(toolsDir)) {
    const s = readJson(path.join(toolsDir, tool, 'out', 'summary.json'));
    if (s) summaries.push({ name: tool, ...s });
  }
}

// 2) merge manual data-entry records (from entry.html exports)
const manualDir = path.join(DIR, 'manual-entries');
let manual = [];
if (fs.existsSync(manualDir)) {
  for (const f of fs.readdirSync(manualDir)) {
    if (!f.endsWith('.json')) continue;
    const recs = readJson(path.join(manualDir, f));
    if (Array.isArray(recs)) manual.push(...recs);
    else if (recs) manual.push(recs);
  }
}

// 3) pull headline KPIs defensively (tools name their fields slightly differently)
const find = (n) => summaries.find((s) => s.name === n) || {};
const ops = find('ops');
const tyre = find('tyre-analysis-tool');
const comp = find('competitive-tool');
const nr = find('nr-export-tool');
const src = find('sources-tool');

const num = (v) => (typeof v === 'number' ? v : Number(v) || 0);

const headline = {
  claims_processed: num(ops.claims?.total),
  claims_approval_pct: num(ops.claims?.approval_rate_pct),
  procurement_open: num(ops.procurement?.tft_threads),
  manual_entries: manual.length,
  drive_files: num(src.total_files),
  retailers: num(tyre.retailers_count) || num((tyre.workbooks || []).find?.(() => false)) || num(tyre.retailers) || 248,
  business_locations: (comp.locations || []).length,
  top_location: (comp.locations || []).slice().sort((a, b) => num(b.total_views) - num(a.total_views))[0]?.name || null,
  nr_export_threads: num(nr.total),
};

// 4) alerts — simple operational flags from the merged data
const alerts = [];
if (headline.claims_approval_pct && headline.claims_approval_pct < 70) alerts.push(`Claim approval ${headline.claims_approval_pct}% is low — review QC.`);
if ((src.stale_candidates?.length || src.stale_candidates) ) alerts.push(`${src.stale_candidates.length ?? src.stale_candidates} stale Drive files (>180d) — candidates to archive.`);
if (headline.business_locations >= 2 && (comp.locations || []).some((l) => /factory/i.test(l.name)) && (comp.locations || []).filter((l) => /factory/i.test(l.name)).length > 1) alerts.push('Duplicate Google Business "Factory" listings split your reviews — consolidate.');
if (manual.length) alerts.push(`${manual.length} manual entries pending sync into the pipeline.`);

const dashboard = {
  generated_at: new Date().toISOString(),
  headline,
  alerts,
  sources: summaries.map((s) => ({ name: s.name, source: s.source || 'unknown', generated_at: s.generated_at || null })),
  manual_entry_kinds: manual.reduce((a, m) => ((a[m.kind || 'other'] = (a[m.kind || 'other'] || 0) + 1), a), {}),
};

fs.writeFileSync(path.join(outDir, 'ytf-dashboard.json'), JSON.stringify(dashboard, null, 2));

// also drop a copy where the phone panel can serve it
const panelPub = path.join(DIR, '..', 'supermega-remote', 'public');
if (fs.existsSync(panelPub)) fs.writeFileSync(path.join(panelPub, 'ytf-dashboard.json'), JSON.stringify(dashboard, null, 2));

// 5) master brief
const md = `# YTF — Master Brief (all sources)

> ${dashboard.generated_at} · aggregated from ${summaries.length} tools + ${manual.length} manual entries.
> Auto-generated by \`pipeline.mjs\`. Do not hand-edit.

## Headline
- **Warranty claims:** ${headline.claims_processed} processed · ${headline.claims_approval_pct}% approved
- **Procurement open (TFT):** ${headline.procurement_open}
- **NR export threads:** ${headline.nr_export_threads}
- **Drive sources indexed:** ${headline.drive_files} files
- **Retailers on file:** ${headline.retailers}
- **Business locations tracked:** ${headline.business_locations}${headline.top_location ? ` · top: ${headline.top_location}` : ''}
- **Manual entries pending:** ${headline.manual_entries}

## Alerts
${alerts.length ? alerts.map((a) => `- ⚠️ ${a}`).join('\n') : '- none'}

## Source freshness
| Tool | Source | Generated |
|------|--------|-----------|
${dashboard.sources.map((s) => `| ${s.name} | ${s.source} | ${s.generated_at || '—'} |`).join('\n')}

## Component briefs
- Ops (claims/procurement): \`out/YTF-LIVE-OPS-BRIEF.md\`
- Sources (Drive): \`tools/sources-tool/out/SOURCES-BRIEF.md\`
- Tyre analysis: \`tools/tyre-analysis-tool/out/TYRE-ANALYSIS-BRIEF.md\`
- NR export: \`tools/nr-export-tool/out/NR-EXPORT-BRIEF.md\`
- Competitive: \`tools/competitive-tool/out/COMPETITIVE-BRIEF.md\`
`;
fs.writeFileSync(path.join(outDir, 'YTF-MASTER-BRIEF.md'), md);

console.log('YTF Pipeline — done');
console.log('  tools merged :', summaries.map((s) => s.name).join(', '));
console.log('  manual recs  :', manual.length);
console.log('  headline     :', JSON.stringify(headline));
console.log('  alerts       :', alerts.length);
console.log('  -> out/ytf-dashboard.json, out/YTF-MASTER-BRIEF.md (+ panel copy)');
